### ISSUE TITLE
Post to github functionality broken in DEV environment

### ISSUE THREAD

**Issue by trevorjpuckett** [precision-sustainable-ag/dst-feedback-api#16]
**What's wrong**
Post user feedback to github issues broken in dev environment

**What done looks like**
endpoint returns success and issues are created in github.

**Where the changes need to be made**
unclear

**Comment by trevorjpuckett** [comment]
This is the error being logged when failure occurs:
```json
{
    "error": "error:0909006C:PEM routines:get_name:no start line",
    "stack": "Error: error:0909006C:PEM routines:get_name:no start line\n    at Sign.sign (node:internal/crypto/sig:131:29)\n    at Object.sign (/node_modules/jsonwebtoken/node_modules/jwa/index.js:152:45)\n    at Object.jwsSign [as sign] (/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:32:24)\n    at Object.module.exports [as sign] (/node_modules/jsonwebtoken/sign.js:204:16)\n    at getToken (/node_modules/universal-github-app-jwt/dist-node/index.js:13:23)\n    at Object.githubAppJwt (/node_modules/universal-github-app-jwt/dist-node/index.js:35:23)\n    at getAppAuthentication (/node_modules/@octokit/auth-app/dist-node/index.js:21:59)\n    at hook (/node_modules/@octokit/auth-app/dist-node/index.js:314:15)\n    at /node_modules/before-after-hook/lib/register.js:25:15\n    at runMicrotasks (<anonymous>)"
}
```

`error:0909006C:PEM routines:get_name:no start line` seems to suggest that the Octokit Auth is failing, most likely failing due to the private key  because it mentions " at Object.module.exports [as sign] (/node_modules/jsonwebtoken/sign.js:204:16)\n    at getToken"

I checked private key variable in Azure to ensure it was entered properly, re-deployed and issue remains. 
this is due to Azures limitation with not supporting multi-lined variables. 

### Solution

Store Private key variable as base64 encoded and decode the .env variable in the code base config file.
